Update motorola_cedric.xml
Halium/halium-devices pull request #211
Opened 2020-04-03 18:47 UTC by luka177

Moved to active fork.

2021-02-11 09:54 UTC, Vince1171 requested changes

2021-02-11 09:54 UTC, Vince1171 commented on manifests/motorola_cedric.xml
> +		fetch="https://github.com/ubports-on-cedric"
you mean https://github.com/halium-on-cedric ;)
https://github.com/ubports-on-cedric => 404
please amend your commit and force push

2021-02-11 10:42 UTC, luka177 commented on manifests/motorola_cedric.xml
> +		fetch="https://github.com/ubports-on-cedric"
oh lol yes, it was renamed

2021-02-23 19:22 UTC, Vince1171 commented on manifests/motorola_cedric.xml
> +		fetch="https://github.com/ubports-on-cedric"
do you plan to change your PR?

2021-02-24 08:14 UTC, luka177 commented on manifests/motorola_cedric.xml
> +		fetch="https://github.com/ubports-on-cedric"
yes i do, sorry currently my time is limited

2021-02-26 13:21 UTC, Vince1171 commented
LGTM

2021-02-26 13:21 UTC, merged