added device tree for building Halium for FP3
Halium/halium-devices pull request #254
Opened 2020-09-27 19:00 UTC by luksus42

2021-02-10 10:40 UTC, Vince1171 requested changes

2021-02-10 10:40 UTC, Vince1171 commented on manifests/fairphone_FP3.xml
> +    <project path="device/fairphone/FP3" name="luksus42/android_device_fairphone_FP3" fetch="https://github.com/luksus42/android_device_fairphone_FP3" revision="halium-9.0"/>
please format it like 
`<project path="device/fairphone/FP3" name="luksus42/android_device_fairphone_FP3"  revision="halium-9.0" remote="hal" />`
if you add `remote="hal"` you can remove all fetch's

and I suggest to amend the commit and then force push it

2021-02-10 19:13 UTC, luksus42 commented
Not sure about the format, but I removed the fetch's and added the remote attributes.

2021-02-11 09:19 UTC, Vince1171 commented
> Not sure about the format, but I removed the fetch's and added the remote attributes.

LGTM

2021-02-11 09:19 UTC, merged