Add Lenovo Tab 3 8 850M manifest
Halium/halium-devices pull request #264
Opened 2020-11-13 14:40 UTC by aL31cS

2021-02-10 10:12 UTC, Vince1171 requested changes

2021-02-10 10:12 UTC, Vince1171 commented on manifests/lenovo_tab3.xml
> +<remote name="mygit"
can you please change the remote name to `aL31cS`? `mygit` is too generic

2021-02-10 12:59 UTC, aL31cS commented on manifests/lenovo_tab3.xml
> +<remote name="mygit"
Ok

2021-02-10 16:45 UTC, Vince1171 commented
can you regroup all commits in one and forcepush? (named `Add Lenovo Tab 3 850M manifest`)

2021-02-11 15:41 UTC, aL31cS commented
> can you regroup all commits in one and forcepush? (named `Add Lenovo Tab 3 850M manifest`)

Done

2021-02-14 16:42 UTC, aL31cS commented
Yes

mie., 10 feb. 2021, 18:45 Vince1171 <notifications@github.com> a scris:

> can you regroup all commits in one and forcepush? (named Add Lenovo Tab 3
> 850M manifest)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Halium/halium-devices/pull/264#issuecomment-776848425>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIYJYYXNXCCUFS5VTKP5EJTS6KZ4BANCNFSM4TUU5S6Q>
> .
>

2021-02-19 14:38 UTC, Vince1171 commented
I've removed the extra commits ;-)

2021-02-19 14:38 UTC, merged