Let FP2 use ubports recovery image
Halium/halium-devices pull request #274
Opened 2020-12-30 15:02 UTC by jonnius

This MR adjusts the FP2 manifest to use the ubports recovery image.

2021-02-11 10:12 UTC, Vince1171 requested changes

2021-02-11 10:12 UTC, Vince1171 commented on manifests/fairphone_FP2.xml
> +    <project path="bootable/recovery" name="android_bootable_recovery" remote="ubp" />
please use the `hal` remote and `name="ubports/REPONAME"` instead of creating a new remote
like
`<project path="bootable/recovery" name="ubports/android_bootable_recovery" remote="hal" revision="halium-7.1" />`

2021-02-11 10:12 UTC, Vince1171 commented on manifests/fairphone_FP2.xml
> +    <project path="bootable/recovery" name="android_bootable_recovery" remote="ubp" />
and I suggest to amend the commit and force push instead of push a second commit

2021-02-14 17:02 UTC, jonnius commented on manifests/fairphone_FP2.xml
> +    <project path="bootable/recovery" name="android_bootable_recovery" remote="ubp" />
Done. Thanks for the advise.

2021-02-14 17:21 UTC, jonnius commented on manifests/fairphone_FP2.xml
> +    <project path="bootable/recovery" name="android_bootable_recovery" remote="ubp" />
Now I run into `error: Cannot checkout ubports/android_bootable_recovery: GitError: None: remote hal does not have refs/heads/halium-7.1`...

2021-02-15 13:12 UTC, Vince1171 commented on manifests/fairphone_FP2.xml
> +    <project path="bootable/recovery" name="android_bootable_recovery" remote="ubp" />
I just tried your manifest on my machine. No issue on my side...

2021-02-15 17:47 UTC, jonnius commented on manifests/fairphone_FP2.xml
> +    <project path="bootable/recovery" name="android_bootable_recovery" remote="ubp" />
No idea what is wrong with my local dir. Will have to set it up fresh probably...

2021-02-15 21:37 UTC, merged